config/routes.rb
Rails.application.routes.draw do
  resources :trainings do
  	resources :exercises
  end
  root 'trainings#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :training
end

app/models/training.rb
class Training < ActiveRecord::Base
	has_many :exercises, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	def create
		@training = Training.find(params[:training_id])
		@exercise = @training.exercises.create(params[:exercise].permit(:name, :sets, :reps))

		redirect_to training_path(@training)
	end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
	before_action :find_training, only: [:show, :edit, :update, :destroy]


	def index
		@trainings = Training.all.order("created_at DESC")
	end

	def show
	end

	def new
		@training = Training.new
	end

	def create
		@training = Training.new(training_params)
		if @training.save
			redirect_to @training
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @training.update(training_params)
			redirect_to @training
		else
			render 'edit'
		end
	end

	def destroy
		@training.destroy
		redirect_to root_path
	end

	private

	def training_params
		params.require(:training).permit(:date, :workout, :length)
	end

	def find_training
		@training = Training.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps

app/views/exercises/_form.html.haml
= simple_form_for([@training, @training.exercises.build]) do |f|
	= f.input :name, input_html: {class: "form-control" }
	= f.input :sets, input_html: {class: "form-control" }
	= f.input :reps, input_html: {class: "form-control" }
	%br/
	= f.submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Training Log Application
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-header
				= link_to "Training Log", root_path, class: "navbar-brand"
			.nav.navbar-nav.navbar-right
				= link_to "New Training", new_training_path, class: "navbar-link"
	.container
		= yield

app/views/trainings/_form.html.haml
= simple_form_for(@training, html: {class: 'form-horizontal'}) do |f|
	= f.input :date, label: "Date"
	= f.input :workout, label: "What area did you workout?", input_html: {class: "form-control" }
	= f.input :length, label: "How long was the training", input_html: {class: "form-control" }
	%br
	= f.button :submit

app/views/trainings/edit.html.haml
%h1 Edit Workout

= render 'form'

= link_to "Cancel", root_path

app/views/trainings/index.html.haml
#index_workouts
	- @trainings.each do |training|
		%h2= link_to training.date.strftime("%A %B %d"), training
		%h3
			%span Workout:
			= training.workout

app/views/trainings/new.html.haml
%h1 New Workout

= render 'form'

= link_to "Cancel", root_path

app/views/trainings/show.html.haml
#training
	%p= @training.date
	%p= @training.workout
	%p= @training.length

#exercises
	%h2 Exercises
	= render @training.exercises

	%h3 Add an exercise
	= render "exercises/form"

	= link_to "Back", root_path
	= link_to "Edit", edit_training_path(@training)
	= link_to "Delete", training_path(@training), method: :delete, data: { confirm: "Are you sure?" }